### ISSUE TITLE
Animation of page navigation not working 

### ISSUE THREAD

**Issue by Gardens18** [creativetimofficial/material-kit-react-native#11]
When the "get pro version" button is clicked in PRO page, it does not navigate with "slide animation" . But it animation works in that same "get pro version" button when we go to the PRO page from **HOME page**. This is weird behavior , kindly identify the cause and resolve , so that we could the same fix in our real App which is being built based on this template.

**Comment by palingheorghe** [comment]
Hi @Gardens18 ! Thank you for being interested in our products! The way the PRO screen moves to the second screen was an intended behaviour. What kind of behaviour were you expecting more exactly?
