### ISSUE TITLE
[Bug] _xdl(...).ProjectUtils.readConfigJsonAsync is not a function

### ISSUE THREAD

**Issue by LaoTsing** [creativetimofficial/material-kit-react-native#15]
### Version
last
### Reproduction link
http://not_started
### Operating System
ubuntu
### Device
android
### Browser & Version
npm 6.13
expo 3.4.1
### Steps to reproduce
expo start
### What is expected?
Starting project at material-kit-react-native-master
_xdl(...).ProjectUtils.readConfigJsonAsync is not a function
Set EXPO_DEBUG=true in your env to view the stack trace.

### What is actually happening?
i try other native project and error is still

---
### Solution
downgrade expo to 3.0.2

**Comment by palingheorghe** [comment]
Hi @LaoTsing ! Thank you for being interested in our products! As far as I can see this is a problem with Expo and not our app. By downgrading expo, did you mean expo-cli? 

Thanks,
Alin 🤙🏽

**Comment by LaoTsing** [comment]
> Hi @LaoTsing ! Thank you for being interested in our products! As far as I can see this is a problem with Expo and not our app. By downgrading expo, did you mean expo-cli?
> 
> Thanks,
> Alin 🤙🏽

Yes, it is expo-cli

**Comment by palingheorghe** [comment]
@LaoTsing Yes, this is an expo-cli issue so it has nothing to do with our App. We'll need to wait for an update from `expo-cli`. As far as I can see there are more issues opened [here](https://github.com/expo/expo-cli/issues/1233). 

Thanks, 
Alin
