### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by matthewfu** [creativetimofficial/material-kit-react-native#16]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When I run npm start after npm install it should start expo server correctly.

# Current Behavior

Starting project at material-kit-pro-react-native-v1.4.0
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
ConfigUtils.configFilenameAsync is not a function
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rn-material-kit-pro@1.4.0 start: `cross-env REACT_EDITOR=code expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rn-material-kit-pro@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

* Device: MPBR
* Operating System: MacOS 10.15.1
* Browser and Version:  Node v10.17.0, expo-cli 3.9.1

**Comment by palingheorghe** [comment]
Hi @matthewfu ! 

Thank you for your interest in our products! This is not a problem with our product but this should solve the issue. 

Try the following commands: 
- `npm cache clean --force`
- delete node_modules folder
- delete package-lock.json file
- `npm install`

I hope this helped you out!
Thanks,
Alin
