### ISSUE TITLE
Metro Bundler process exited with code 1

### ISSUE THREAD

**Issue by thilinaucsc** [creativetimofficial/material-kit-react-native#17]
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

**Comment by palingheorghe** [comment]
Hi @thilinaucsc ! 
Thank you for your interest in our products! Could you please offer us more information about your problem? What was the process of installing the project? What type of packages have you installed? What type of simulator/OS are you using?

**Comment by jcuervas** [comment]
I have this issue also. Just uncompressed free version to a folder and
`npm install -g expo-cli`
`npm install`
`expo start`

My OS is windwos 10. No Simulator or emulator tryed

**Comment by palingheorghe** [comment]
Hi @jcuervas ! Thank you for your interest in our products! As far as I can see this error is a react-native one and could be solved by updating some packages from the core library: https://github.com/facebook/react-native/issues/26969 
Thanks!
