### ISSUE TITLE
[Question] react-navigation-stack v2 upgrade 

### ISSUE THREAD

**Issue by robertqin86** [creativetimofficial/material-kit-react-native#18]
Hi there, I would like to ask if there are any plans in the pipeline to upgrade `react-navigation-stack` to version 2? There are a couple of breaking changes in version 2 that breaks this template. 

I'm in no hurry to upgrade it but would like to ask if there are plans to upgrade to use the latest `react-navigation` and `react-navigation-stack`. If there isn't, then I would have to figure out the breaking changes myself.

**Comment by palingheorghe** [comment]
Hi @robertqin86 ! Thank you for your interest in our products! Yes, we know of the breaking changes brought by `react-navigation-stack` and we're trying to solve them right as I'm writing this message. So you could expect an update the following days. 

Thanks,
Alin 🧜🏽‍♂️

**Comment by palingheorghe** [comment]
The product is now updated to v1.5.0 which solved all `react-navigation` issues. Thank you for your patience!
