### ISSUE TITLE
Windows 10 - Compile issues on specific modules

### ISSUE THREAD

**Issue by dnorthrupva** [creativetimofficial/material-kit-react-native#19]
Bypassing template since this is a partial question - I'm running Win 10, and already found the bug issues about using node 12.9 or newer - I downgraded to 12.9 to get compilation to work, however I am getting an error on every attempt to open it to a different module.

`npm install` spits out a plethora of warnings but no errors.

When it warned me about one specific package, looking for support I found that running `expo install react-native-screens` fixed it, but now I am on another module. 

Is this a known issue, or is there a way for me to expo install 'all' modules as needed?

**Comment by palingheorghe** [comment]
Hi @dnorthrupva, 

Thank you for trying out our products! Having the error log would help tremendously with this issue. Based on your description of the issue I think this would help:
1. Re-download our product
2. Open `packages.json` and delete all instances of `^`
3. `npm install`
4. `expo r -c`
5. $$$ -> the app should be working with no issues whatsoever

I hope this answers your question and solves your problem.

Thanks,
Alin

**Comment by palingheorghe** [comment]
The product is now updated to v1.5.0 which solved all `react-navigation` issues. Thank you for your patience!
