### ISSUE TITLE
Failed at the rn-material-kit-free@1.4.0 start script.

### ISSUE THREAD

**Issue by chenshuxian** [creativetimofficial/material-kit-react-native#20]
I got Err can you help me solve it, this is me err message
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rn-material-kit-free@1.4.0 start: `cross-env REACT_EDITOR=code expo start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rn-material-kit-free@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-02-16T09_10_30_649Z-debug.log

my package Json is:
{
  "name": "rn-material-kit-free",
  "version": "1.4.0",
  "description": "Material Kit React Native. Coded by Creative Tim",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "cross-env REACT_EDITOR=code expo start",
    "android": "cross-env REACT_EDITOR=code expo start --android",
    "ios": "cross-env REACT_EDITOR=code expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "expo-asset": "~7.0.0",
    "expo-font": "~7.0.0",
    "expo-linear-gradient": "~7.0.0",
    "galio-framework": "^0.6.3",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0",
    "cross-env": "^5.2.0",
    "expo-cli": "^2.4.0",
    "jest-expo": "^35.0.0"
  },
  "bugs": {
    "url": "https://github.com/creativetimofficial/material-kit-react-native/issues"
  },
  "homepage": "https://demos.creative-tim.com/material-kit-react-native/"
}

**Comment by palingheorghe** [comment]
Hi @chenshuxian ,
Thank you for trying out our products! Before going further I have to ask you what were the steps you've taken to get to the above error. Have you installed the packages via `npm install`? Before that you should remove all `^` symbols from your `package.json` file just to be 100% sure everything is going to work as intended.

Thanks,
Alin 🤙🏽

**Comment by chenshuxian** [comment]
thx your help @palingheorghe solved
