### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by dhirenchotwani** [creativetimofficial/material-kit-react-native#22]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

npm modules to be installed after i hit npm install

# Current Behavior

installs some of the files and at some point displays message unexpected end of file and shuts npm install

# Failure Information (for bugs)

npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated joi@14.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
npm WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! code Z_BUF_ERROR

**npm ERR! errno -5
npm ERR! zlib: unexpected end of file**

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2020-02-27T08_08_17_882Z-debug.log

## Context

Downloaded the Material kit starter pack for react native and followed the same steps as mentioned in the documentation

* Device: HP au 003tx
* Operating System: Windows 10
* Browser and Version:  Chrome

## Failure Logs
Attached above

**Comment by palingheorghe** [comment]
Hi @dhirenchotwani, 
Thank you for being interested in our products. You should try `npm cache clean --force`, this is a problem with your npm configuration. I hope this solves your issue. 

Thanks,
Alin 🧜🏽‍♂️
