### ISSUE TITLE
icon.png is missing in assets folder

### ISSUE THREAD

**Issue by NirajSavaliya** [creativetimofficial/material-kit-react-native#23]
When I enter command expo start, its showing be below error

material-kit-react-native-master/assets/icon.png for platform: null
Error: Asset not found

**Comment by palingheorghe** [comment]
Hi @NirajSavaliya ,

Thank you for being interested in our products! As you can see the image is supposed to be fetched from `assets/images/icon.png` ([app.json file](https://github.com/creativetimofficial/material-kit-react-native/blob/master/app.json)) and that image is present in that folder. Your problem has probably something to do with cache.

I recommend deleting `node_modules`, `package-lock.json` and `.expo` and then using `npm install` again and start your app with `expo r -c` which should clear the cache. 

Thanks,
Alin

**Comment by palingheorghe** [comment]
We've updated the app to v1.6.0 so everything should work as intended now. Thank you for your patience!
