### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by azngordy7** [creativetimofficial/material-kit-react-native#24]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Project compiles and displays the material kit UI in browser

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Failed to compile.
../material-kit-react-native-master/node_modules/react-native-modal-dropdown/components/ModalDropdown.js
Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator' in '..\material-kit-react-native-master\node_modules\react-native-modal-dropdown\components'

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Completed installation steps on https://demos.creative-tim.com/material-kit-react-native/docs/#/install
2. npm install
3. expo r -c
4. In expo GUI, click 'Run in web browser'
5.  (error occurs)

## Context

* Operating System: Windows 10
* Browser and Version: Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)
* Expo: 3.17.24
* npm: 6.14.4

## Failure Logs

 Local:            http://localhost:19006/
  On Your Network:  http://192.168.1.17:19006/

Note that the development build is not optimized.

 › To create a production build, run expo build:web
 › Press Ctrl+C to exit.

 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
 web  Failed to compile.
O:/App Projects/RN Test/material-kit-react-native-master/node_modules/react-native-modal-dropdown/components/ModalDropdown.js
Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator' in 'O:\App Projects\RN Test\material-kit-react-native-master\node_modules\react-native-modal-dropdown\components'

Compiling...

× Expo Webpack
  Compiled with some errors in 3.97s
 web  Failed to compile.
O:/App Projects/RN Test/material-kit-react-native-master/node_modules/react-native-modal-dropdown/components/ModalDropdown.js
Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator' in 'O:\App Projects\RN Test\material-kit-react-native-master\node_modules\react-native-modal-dropdown\components'

**Comment by palingheorghe** [comment]
Hi @azngordy7 ,

Thank you for being interested in our products! We haven't made any tests on the browser but I think everything should work properly if you'd delete `react-native-modal-dropwdown` from `package.json` and all the files using that library. After that, reinstall all packages and start the app with `expo r -c` this will ensure you to clear the cache. 

Thanks,
Alin

**Comment by azngordy7** [comment]
Hi Alin (@palingheorghe),

I've followed your advice and removed `react-native-modal-dropdown` from `package-json` and removed the reference to this package in O:\materialkit\components\Select.js. However, I am still having issues compiling. I receive the following error message:

>  web  Failed to compile.
>  O:/materialkit/components/Tabs.js
>  Module not found: Can't resolve 'react-native-web/dist/exports/Animated' in 'O:\materialkit\components'

Any further advice would be much appreciated.

Many thanks,
Gordy.

**Comment by palingheorghe** [comment]
We've updated the app to v1.6.0 so everything should work as intended now. Thank you for your patience!

**Comment by RoshanRoyal** [comment]
this issue still exists with 1.6.0 version any help would be appreciated

**Comment by AlaRaies** [comment]
this issue exists in 1.7.0 with no available fix ( i'm facing the same issue in argon template)

**Comment by Naphier** [comment]
Still a problem :(
