### ISSUE TITLE
Statusbar not changing, always dark

### ISSUE THREAD

**Issue by william-levi** [creativetimofficial/material-kit-react-native#26]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

the drawer should be full screen (see picture below, as you can see the statusbar when the drawer opens) this one is from the old material-kit. 
![Screenshot_20200706_071701_com material materialfree](https://user-images.githubusercontent.com/25534399/86544416-3a570f00-bf59-11ea-9bfd-1a04ad75306f.jpg)

# Current Behavior

What is the current behavior?

the statusbar is always black(see picture) it is not full screen

![Screenshot_20200706_071714_host exp exponent](https://user-images.githubusercontent.com/25534399/86544459-a9ccfe80-bf59-11ea-887e-b49e20f42bb4.jpg)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
clone the repo
2. step 2
run with expo
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Huawei nova 3i
* Operating System: Android

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by william-levi** [comment]
also 1 more.. the padding i think is not correctly applied, in header and in drawer

**Comment by palingheorghe** [comment]
Hi @william-levi ,

Thank you for your interest in our products! Sorry for the late reply, I'm pretty sure this [package](https://docs.expo.io/versions/latest/sdk/status-bar/) should help you out with your issue. This is an Expo package so you'd have to still use Expo in order to use it. The change happened because of Expo updates so I think this would be the best way for you to customise the app. 

Thanks,
Alin
