### ISSUE TITLE
iPad Pro Portrait Layout Issue

### ISSUE THREAD

**Issue by lphomiej** [creativetimofficial/material-kit-react-native#28]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

On iPad pro, layout should be visible in landscape and portrait mode.

# Current Behavior

What is the current behavior? Landscape mode works fine, but in Portrait, it cuts off the side. 

# Failure Information (for bugs)

Using Expo, iPad Pro (2nd gen).

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone repo
2. npm install
3. expo start
4. Open in expo in iPad Pro
5. Rotate screen to portrait mode, and body layout is cut off on both sides (cards, search bar, etc)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iPad Pro
* Operating System: iOS 14.2
* Browser and Version: Expo

**Comment by hetmann** [comment]
@lphomiej Hey, sorry for the long wait ... what I can tell you is that the current codebase wasn't made/tested on tabled resolution.

This should be fixed/done manually by your team/developers using `onLayout` method.
