### ISSUE TITLE
annoying border in the header

### ISSUE THREAD

**Issue by Gardens18** [creativetimofficial/material-kit-react-native#3]
When the "header" is removed from Login  screen , it shows a grey border in the header, kindly help to remove it.

<img width="479" alt="Screen Shot 2019-06-20 at 2 57 12 PM" src="https://user-images.githubusercontent.com/41816775/59847779-264f6800-936c-11e9-82b3-3bc6ccebe79a.png">

`
const LoginStack = createStackNavigator({ 
  Login: {
    screen: LoginScreen,
  },

}, {
  cardStyle: { backgroundColor: '#d9dfec'},
  transitionConfig,
})

const HomeStack = createStackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: ({navigation}) => ({
      header: <Header  title="Welcome" navigation={navigation} />,
    })
   },
},
{
  cardStyle: { 
    backgroundColor: '#d9dfec', //this is the backgroundColor for the app
  },
  transitionConfig,
});`

**Comment by palingheorghe** [comment]
Hi @Gardens18 ! There is no screen called `LoginScreen` inside `material-kit-react-native`. Please open up an issue following the issue_template for the correct product. 

Thanks,
Alin

**Comment by Gardens18** [comment]
That LoginScreen is just copy of the HomeScreen that comes with the template. The problem is in the header, if you remove <header> from any page, it shows that grey border.

**Comment by palingheorghe** [comment]
Hi @Gardens18 ! This is the basic behaviour of the `createStackNavigator` used in `react-navigation`. If you'd try using the screen in a `createDrawerNavigator` function you'll see that this doesn't happen anymore. You can read more about how to use `createStackNavigator` here: [https://reactnavigation.org/docs/en/headers.html](https://reactnavigation.org/docs/en/headers.html).

Thanks, 
Alin

**Comment by Gardens18** [comment]
" headerTransparent: true "
Great, it worked , thank you

**Comment by palingheorghe** [comment]
No problem! Glad I could help!
