### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by Alta1re** [creativetimofficial/material-kit-react-native#30]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I expected, that npm i will install all dependencies.

# Current Behavior

Error message.

# Failure Information (for bugs)

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: rn-material-kit-free@1.8.0
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"^16.13.1" from the root project
npm ERR!   peer react@"16.13.1" from jest-expo@40.0.2
npm ERR!   node_modules/jest-expo
npm ERR!     dev jest-expo@"^40.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"*" from jest-expo@40.0.2
npm ERR!   node_modules/jest-expo
npm ERR!     dev jest-expo@"^40.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/svenhager/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svenhager/.npm/_logs/2021-04-24T10_32_57_597Z-debug.log
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. download the package from GitHub
2. install expo-cli on system
3. navigate to the directory, and npm install

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: MBP 2020 intel version
* Operating System: MacOS 11.2.3 BigSur
* Browser and Version: Not relevant (Chrome/Safari/Firefox all up to date)

## Failure Logs

0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i', 'react' ]
1 info using npm@7.6.3
2 info using node@v14.16.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/svenhager/Github/material-kit-react-native/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/svenhager/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 5ms
19 verbose npm-session c640824fb67a2034
20 timing npm:load Completed in 9ms
21 timing arborist:ctor Completed in 1ms
22 timing arborist:ctor Completed in 1ms
23 timing idealTree:init Completed in 11ms
24 timing idealTree:userRequests Completed in 1ms
25 silly idealTree buildDeps
26 silly fetch manifest babel-preset-expo@^8.3.0
27 http fetch GET 304 https://registry.npmjs.org/babel-preset-expo 1002ms (from cache)
28 silly fetch manifest cross-env@^7.0.0
29 http fetch GET 304 https://registry.npmjs.org/cross-env 71ms (from cache)
30 silly fetch manifest expo-cli@^3.11.7
31 http fetch GET 304 https://registry.npmjs.org/expo-cli 57ms (from cache)
32 silly fetch manifest jest-expo@^40.0.0
33 http fetch GET 200 https://registry.npmjs.org/jest-expo 1129ms
34 silly fetch manifest react@^16.13.1
35 http fetch GET 304 https://registry.npmjs.org/react 66ms (from cache)
36 silly fetch manifest react@16.13.1
37 silly fetch manifest react-native@*
38 http fetch GET 200 https://registry.npmjs.org/react-native 249ms
39 timing idealTree Completed in 2645ms
40 timing command:i Completed in 2655ms
41 verbose stack Error: unable to resolve dependency tree
41 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1157:25)
41 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1150:30)
41 verbose stack     at Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:933:30)
41 verbose stack     at async Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1110:11)
41 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:838:11)
41 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
41 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:120:5)
42 verbose cwd /Users/svenhager/Github/material-kit-react-native
43 verbose Darwin 20.3.0
44 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "react"
45 verbose node v14.16.0
46 verbose npm  v7.6.3
47 error code ERESOLVE
48 error ERESOLVE unable to resolve dependency tree
49 error
50 error While resolving: [1mrn-material-kit-free[22m@[1m1.8.0[22m
50 error Found: [1mreact[22m@[1m16.13.1[22m[2m[22m
50 error [2mnode_modules/react[22m
50 error   [1mreact[22m@"[1m^16.13.1[22m" from the root project
50 error   [35mpeer[39m [1mreact[22m@"[1m16.13.1[22m" from [1mjest-expo[22m@[1m40.0.2[22m[2m[22m
50 error   [2mnode_modules/jest-expo[22m
50 error     [33mdev[39m [1mjest-expo[22m@"[1m^40.0.0[22m" from the root project
50 error
50 error Could not resolve dependency:
50 error [35mpeer[39m [1mreact[22m@"[1m17.0.1[22m" from [1mreact-native[22m@[1m0.64.0[22m[2m[22m
50 error [2mnode_modules/react-native[22m
50 error   [35mpeer[39m [1mreact-native[22m@"[1m*[22m" from [1mjest-expo[22m@[1m40.0.2[22m[2m[22m
50 error   [2mnode_modules/jest-expo[22m
50 error     [33mdev[39m [1mjest-expo[22m@"[1m^40.0.0[22m" from the root project
50 error
50 error Fix the upstream dependency conflict, or retry
50 error this command with --force, or --legacy-peer-deps
50 error to accept an incorrect (and potentially broken) dependency resolution.
50 error
50 error See /Users/svenhager/.npm/eresolve-report.txt for a full report.
51 verbose exit 1

**Comment by ac2894** [comment]
I have the same Error
MacOs 11.3.1 BugSur

**Comment by justnajm** [comment]
Same here :(

**Comment by hetmann** [comment]
@Alta1re @ac2894 @justnajm hey guys. This is due to the fact `material-kit-react-native` package uses the following react & react-native version (expo) and there is conflict on the current deps.
```json
"react": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"
```

Solution:
- Update all the dependencies to the latest versions

**Comment by Alta1re** [comment]
This is not helpful. I wanted to buy this package very much, but it´s not running properly, and you even don´t want to help.

**Comment by Alta1re** [comment]
The solution for this:
Use yarn, instead of npm. 
If you use Yarn 2, set the "nodeLinker" to "node-modules".
