### ISSUE TITLE
Warning: Failed prop type: Invalid prop `testID` of type `number` supplied to `Text`, expected `string`.

### ISSUE THREAD

**Issue by vitorcalvi** [creativetimofficial/material-kit-react-native#32]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

Warning: Failed prop type: Invalid prop `testID` of type `number` supplied to `Text`, expected `string`.
at node_modules\react-native\Libraries\LogBox\LogBox.js:173:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\prop-types\checkPropTypes.js:20:6 in printWarning
at node_modules\prop-types\checkPropTypes.js:82:22 in checkPropTypes
at node_modules\react\cjs\react.development.js:1714:20 in validatePropTypes
at node_modules\react\cjs\react.development.js:1813:21 in createElementWithValidation
at node_modules\react-native-modal-dropdown\components\ModalDropdown.js:465:6 in _renderItem
at node_modules\react-native\Libraries\Lists\VirtualizedList.js:2089:20 in CellRenderer#render
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:12478:21 in finishClassComponent
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:12403:43 in updateClassComponent
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19181:22 in beginWork$1
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18085:22 in performUnitOfWork
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18013:38 in workLoopSync
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17977:18 in renderRootSync
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17674:33 in performSyncWorkOnRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
at node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:7267:16 in classComponentUpdater.enqueueSetState
at node_modules\react\cjs\react.development.js:471:2 in Component.prototype.setState
at node_modules\react-native-modal-dropdown\components\ModalDropdown.js:197:9 in show
at node_modules\react-native-modal-dropdown\components\ModalDropdown.js:185:8 in _button.measure$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:462:4 in __invokeCallback
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:127:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:126:4 in invokeCallbackAndReturnFlushedQueue

**Comment by hetmann** [comment]
@vitorcalvi This can be easily fix by wrapping the value using String(_value_) to always convert it to string type.
