### ISSUE TITLE
Please upgrade to SDK 34 with new expo icons

### ISSUE THREAD

**Issue by Gardens18** [creativetimofficial/material-kit-react-native#6]
Please upgrade to SDK 34 with new expo icons

**Comment by palingheorghe** [comment]
Hi @Gardens18 ! The app was updated to SDK 34 please verify our [CHANGELOG](https://github.com/creativetimofficial/material-kit-react-native/releases/tag/v1.3.0).

Alin 🧜🏽‍♂️
