### ISSUE TITLE
Demo is not working in expo snack ide

### ISSUE THREAD

**Issue by stardev24** [creativetimofficial/material-kit-react-native#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest version
- [*] I checked to make sure that this issue has not already been filed
- [*] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

Demo should work in expo and user should able to see exact screens

What is the current behavior?

Demo is not working in expo snack ide and it is showing transparent  blank screen.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone git repo into expo Snack IDE
2. Observe output in device of Snack IDE
3. you get transparent screen instead of actual screen

## Context

expo snack IDE
Android

## Failure Logs

Unable resolve module 'module://components/.js'

**Comment by abdul-hafizh** [comment]
mee too

**Comment by julesmoretti** [comment]
Same here. Demo not working.

**Comment by palingheorghe** [comment]
Hi @julesmoretti @abdul-hafizh @stardev24 ! Thank you for your interest in our products! We think this is a problem with Galio not working on the Expo Snack. Our product `material kit react native` was never intended for Expo Snack so we can't help you with the issue. Once the Galio library is working with Snack, our product should work as well by default.

Thanks,
Alin
